<?php

namespace Container7TYZIQ0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D7IXggxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d7IXggx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d7IXggx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'suiteRepo' => ['privates', 'App\\Repository\\SuiteRepository', 'getSuiteRepositoryService', true],
        ], [
            'doctrine' => '?',
            'suiteRepo' => 'App\\Repository\\SuiteRepository',
        ]);
    }
}
