<?php

namespace Container4o9cSjY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W43e_1iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W43e.1i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W43e.1i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationsRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'suiteRepo' => ['privates', 'App\\Repository\\SuiteRepository', 'getSuiteRepositoryService', true],
        ], [
            'reservationsRepo' => 'App\\Repository\\ReservationRepository',
            'suiteRepo' => 'App\\Repository\\SuiteRepository',
        ]);
    }
}
