<?php

namespace ContainerBBrcKWN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AS0mJT4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aS0mJT4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aS0mJT4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hotel' => ['privates', '.errored..service_locator.aS0mJT4.App\\Entity\\Hotels', NULL, 'Cannot autowire service ".service_locator.aS0mJT4": it needs an instance of "App\\Entity\\Hotels" but this type has been excluded in "config/services.yaml".'],
            'hotelsRepo' => ['privates', 'App\\Repository\\HotelsRepository', 'getHotelsRepositoryService', true],
            'suitesRepo' => ['privates', 'App\\Repository\\SuiteRepository', 'getSuiteRepositoryService', true],
        ], [
            'hotel' => 'App\\Entity\\Hotels',
            'hotelsRepo' => 'App\\Repository\\HotelsRepository',
            'suitesRepo' => 'App\\Repository\\SuiteRepository',
        ]);
    }
}
