<?php

namespace ContainerIHqRdzB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHotelsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aS0mJT4.App\Entity\Hotels' shared service.
     *
     * @return \App\Entity\Hotels
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aS0mJT4": it needs an instance of "App\\Entity\\Hotels" but this type has been excluded in "config/services.yaml".');
    }
}
