<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFTSMvcG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFTSMvcG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFTSMvcG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFTSMvcG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFTSMvcG\App_KernelDevDebugContainer([
    'container.build_hash' => 'FTSMvcG',
    'container.build_id' => '7a4b197e',
    'container.build_time' => 1678800252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFTSMvcG');
