<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD9QSpN8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD9QSpN8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD9QSpN8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD9QSpN8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD9QSpN8\App_KernelDevDebugContainer([
    'container.build_hash' => 'D9QSpN8',
    'container.build_id' => '9e2abd81',
    'container.build_time' => 1677162192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD9QSpN8');
