<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIfxqMOp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIfxqMOp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIfxqMOp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIfxqMOp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIfxqMOp\App_KernelDevDebugContainer([
    'container.build_hash' => 'IfxqMOp',
    'container.build_id' => '700c1b90',
    'container.build_time' => 1678783618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIfxqMOp');
