<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_hotel' => [['id', 'slug'], ['_controller' => 'App\\Controller\\HotelController::index'], [], [['variable', '-', '[^/]++', 'slug', true], ['variable', '/', '[^/\\-]++', 'id', true], ['text', '/hotel']], [], [], []],
    'app_hotel_reservation' => [['id'], ['_controller' => 'App\\Controller\\HotelController::renderReservationForm'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/hotel/reservation']], [], [], []],
    'app_reservation_success' => [['id'], ['_controller' => 'App\\Controller\\HotelController::reservationSuccess'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/hotel/recapitulatif']], [], [], []],
    'app_managment' => [[], ['_controller' => 'App\\Controller\\ManagmentController::index'], [], [['text', '/managment']], [], [], []],
    'app_reservation_managment' => [['id'], ['_controller' => 'App\\Controller\\ManagmentController::reservationsView'], [], [['text', '-reservations'], ['variable', '/', '[^/\\-]++', 'id', true], ['text', '/managment']], [], [], []],
    'app_suite_managment' => [['id'], ['_controller' => 'App\\Controller\\ManagmentController::renderSuiteUpdateForm'], [], [['text', '-suite'], ['variable', '/', '[^/\\-]++', 'id', true], ['text', '/managment']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
